# Generated by Django 4.2.5 on 2023-09-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_slug', models.SlugField(blank=True)),
                ('cat_banner_image', models.ImageField(upload_to='cat_banner_image_upload')),
            ],
        ),
        migrations.CreateModel(
            name='eventName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=90)),
                ('event_slug', models.SlugField(blank=True)),
                ('event_banner_image', models.ImageField(upload_to='event_banner_image_upload')),
                ('event_cat_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categories')),
            ],
        ),
        migrations.CreateModel(
            name='eventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_all_images', models.FileField(upload_to='event_all_image_upload')),
                ('event_cat_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categories')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.eventname')),
            ],
        ),
    ]
