# Generated by Django 4.2.5 on 2023-09-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('static_css_file', models.FileField(blank=True, default='', upload_to='static')),
                ('static_js_file', models.FileField(blank=True, default='', upload_to='static')),
            ],
        ),
    ]
