# Generated by Django 4.2.5 on 2023-09-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_static'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Static',
        ),
    ]
