# Generated by Django 4.2.5 on 2023-09-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categories_eventname_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='event_cat_name',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='eventname',
            name='event_cat_name',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='eventImage',
        ),
        migrations.DeleteModel(
            name='eventName',
        ),
    ]
