# Generated by Django 4.2.5 on 2023-09-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_eventimage_event_cat_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('dude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dude')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.phonetype')),
            ],
        ),
    ]
