# Generated by Django 4.2.5 on 2023-09-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dude_phonetype_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='dude',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='type',
        ),
        migrations.DeleteModel(
            name='Dude',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='PhoneType',
        ),
    ]
