# Generated by Django 4.2.5 on 2023-09-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_static'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Static',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
