# Generated by Django 4.2.5 on 2023-09-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dude_phonetype_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneType',
            new_name='File',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='dude',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='type',
        ),
        migrations.DeleteModel(
            name='Dude',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
