# Generated by Django 4.2.5 on 2023-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_static_remove_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, default='', upload_to='image'),
        ),
    ]
