# Generated by Django 4.2.5 on 2023-09-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
