# Generated by Django 4.2.5 on 2023-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.FileField(blank=True, default='', upload_to='file')),
                ('css', models.FileField(blank=True, default='', upload_to='file')),
                ('js', models.FileField(blank=True, default='', upload_to='file')),
            ],
        ),
    ]
