# Generated by Django 4.2.5 on 2023-09-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_static'),
    ]

    operations = [
        migrations.DeleteModel(
            name='static',
        ),
    ]
